# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39bde5501d4576695bd681110ec1cd806d34a1931b1448a2f0b0eabb0932a2074f1ee56880b822f5c4e1422176008ca3edd61c257f6edb6370a5062d49290c9f

test:
  secret_key_base: 55c6962988dc4e18005e61c7830bbe165bec57d93ebc198113e0005ad3ba12e22ac77f00945550e58606ab7735585ba94955f5c8a0d33df47db0baaf2295c2a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
